/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gemengqin' at '2/1/17 9:21 PM' with Gradle 2.14.1
 *
 * @author gemengqin, @date 2/1/17 9:21 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
